In [34]:
import numpy as np

In [35]:
Basic_slicing = np.array([20, 30, 40, 50, 60])
Basic_slicing[1:4]

array([30, 40, 50])

In [37]:
Basic_slicing[-4:-1]

array([30, 40, 50])

In [38]:
Basic_slicing[: : -1]

array([60, 50, 40, 30, 20])

In [42]:
step_slicing = np.arange(1, 21)
step_slicing

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20])

In [49]:
even_nums = step_slicing % 2 == 0
even_nums

array([ True,  True,  True,  True,  True,  True,  True,  True,  True,
        True])

In [50]:
step_slicing = step_slicing[even_nums]
step_slicing

array([ 2,  4,  6,  8, 10, 12, 14, 16, 18, 20])

In [51]:
Third_element_from_2 = np.arange(1, 21)

In [52]:
Third_element_from_2

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20])

In [53]:
Third_element_from_2[2 : : 3]

array([ 3,  6,  9, 12, 15, 18])

In [55]:
Last_5_nums_reversed = np.arange(1, 21)
Last_5_nums_reversed

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20])

In [60]:
Last_5_nums_reversed[-5 :][: : -1]

array([20, 19, 18, 17, 16])

In [61]:
conditional_indexing = np.array([12, 5, 18, 7, 20, 3])
conditional_indexing

array([12,  5, 18,  7, 20,  3])

In [66]:
grater_than_zero = conditional_indexing > 0
grater_than_zero

array([ True,  True,  True,  True,  True,  True])

In [67]:
index_position_less_10 = np.array([12, 5, 18, 7, 20, 3])
index_position_less_10

array([12,  5, 18,  7, 20,  3])

In [68]:
index_position_less_10 = np.where(index_position_less_10 < 10)
index_position_less_10

(array([1, 3, 5]),)

In [76]:
replace_odd = np.array([12, 5, 18, 7, 20, 3])
replace_odd[replace_odd % 2 == 1] = -1

In [77]:
replace_odd

array([12, -1, 18, -1, 20, -1])

In [90]:
Fancy_indexing = np.array([100, 200, 300, 400, 500])
idx = [0, 3, 1]

In [91]:
Fancy_indexing[idx]

array([100, 400, 200])

In [92]:
# 2D ARRAY SLICING

In [101]:
twoD_array = np.array(
    [
        [1, 2, 3, 4],
        [5, 6, 7, 8],
        [9, 10, 11, 12]
    ]
)

In [102]:
twoD_array

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [107]:
sliced = twoD_array[1 : , 1 : 3]

In [108]:
sliced

array([[ 6,  7],
       [10, 11]])

In [111]:
Last_col = twoD_array[:, 3]

In [112]:
Last_col

array([ 4,  8, 12])

In [121]:
Reverse_rows = twoD_array[: : -1]
Reverse_rows

array([[ 9, 10, 11, 12],
       [ 5,  6,  7,  8],
       [ 1,  2,  3,  4]])

In [122]:
Reverse_col = twoD_array[:, ::-1]
Reverse_col

array([[ 4,  3,  2,  1],
       [ 8,  7,  6,  5],
       [12, 11, 10,  9]])

In [129]:
mat = [
    [1, 2, 3],
    [4, 5, 6],
    [7, 8, 9]
]

diagonal_elements = []
for i in range(len(mat)):
    diagonal_elements.append(mat[i][i])

print(diagonal_elements)

[1, 5, 9]


In [131]:
arr = np.arange(1, 100, 10)
arr

array([ 1, 11, 21, 31, 41, 51, 61, 71, 81, 91])

In [133]:
indices_greater_40 = np.where(arr > 40)
indices_greater_40 # This print indexes of the arr

(array([4, 5, 6, 7, 8, 9]),)

In [135]:
arr[3 : 8] = 0

In [136]:
arr

array([ 1, 11, 21,  0,  0,  0,  0,  0, 81, 91])

In [137]:
mixed_index = np.arange(1, 17).reshape(4, 4)
mixed_index

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [13, 14, 15, 16]])

In [139]:
mixed_index[0, 0]

np.int64(1)

In [140]:
mixed_index[1, 2]

np.int64(7)

In [141]:
mixed_index[3, 1]

np.int64(14)

In [147]:
mixed_index[: , 1:]

array([[ 2,  3,  4],
       [ 6,  7,  8],
       [10, 11, 12],
       [14, 15, 16]])

In [148]:
replace_slice = np.arange(10)
replace_slice

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [156]:
replace_slice[3 : 7] = [100, 200, 300, 400]

In [157]:
replace_slice

array([  0,   1,   2, 100, 200, 300, 400,   7,   8,   9])