In [9]:
import numpy as np

In [10]:
# ARTHIMATIC OPERATIONS

In [11]:
a1 = np.array([1, 2, 3, 4, 5])
a2 = np.array([6, 7, 8, 9, 10])

In [12]:
a1 + a2

array([ 7,  9, 11, 13, 15])

In [13]:
a1 - a2

array([-5, -5, -5, -5, -5])

In [14]:
a1 * a2

array([ 6, 14, 24, 36, 50])

In [15]:
a1 / a2

array([0.16666667, 0.28571429, 0.375     , 0.44444444, 0.5       ])

In [16]:
a1 // a2

array([0, 0, 0, 0, 0])

In [17]:
a1 ** a2

array([      1,     128,    6561,  262144, 9765625])

In [18]:
# BROADCASTING

In [19]:
l = [10, 20, 30, 40]
arr = np.array(l)

In [20]:
arr

array([10, 20, 30, 40])

In [21]:
arr2 = np.arange(1, 26).reshape(5, 5)

In [22]:
arr2

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25]])

In [23]:
arr2 += 10

In [24]:
arr2

array([[11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25],
       [26, 27, 28, 29, 30],
       [31, 32, 33, 34, 35]])

In [25]:
# DEEP AND SHALLOW COPY

In [26]:
a = np.arange(1, 21)

In [27]:
a

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20])

In [28]:
sliced = a[:5]
sliced *= 10
sliced

array([10, 20, 30, 40, 50])

In [29]:
a[4:6] * 10

array([500,  60])

In [30]:
a
b = a.copy()

In [31]:
b

array([10, 20, 30, 40, 50,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20])

In [32]:
b[0] = 99

In [33]:
b

array([99, 20, 30, 40, 50,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20])

In [34]:
a

array([10, 20, 30, 40, 50,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20])

In [35]:
# MATRIX OPERATION

In [38]:
A = np.array([[1,2], [3, 4]])
B = np.array([[5, 6], [7, 8]])

In [40]:
dot_product = np.dot(A, B)
dot_product

array([[19, 22],
       [43, 50]])

In [41]:
A.T

array([[1, 3],
       [2, 4]])

In [42]:
B.T

array([[5, 7],
       [6, 8]])

In [43]:
# ADVANCE ARRAY  MANUPLATION

In [44]:
# Stacking the array

In [45]:
A = np.array([[1,2], [3, 4]])
B = np.array([[5, 6], [7, 8]])

In [46]:
horizontal_stack = np.hstack((A, B))
horizontal_stack

array([[1, 2, 5, 6],
       [3, 4, 7, 8]])

In [47]:
vertical_stack = np.vstack((A, B))
vertical_stack

array([[1, 2],
       [3, 4],
       [5, 6],
       [7, 8]])

In [50]:
col_stack = np.column_stack((A, B))
col_stack

array([[1, 2, 5, 6],
       [3, 4, 7, 8]])

In [51]:
# SPLITTING ARRAY

In [52]:
c = np.arange(16).reshape(4, 4)
c

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [55]:
horizontal_split = np.hsplit(c, 4)
horizontal_split

[array([[ 0],
        [ 4],
        [ 8],
        [12]]),
 array([[ 1],
        [ 5],
        [ 9],
        [13]]),
 array([[ 2],
        [ 6],
        [10],
        [14]]),
 array([[ 3],
        [ 7],
        [11],
        [15]])]

In [58]:
vertical_split = np.vsplit(c, 4)

In [59]:
vertical_split

[array([[0, 1, 2, 3]]),
 array([[4, 5, 6, 7]]),
 array([[ 8,  9, 10, 11]]),
 array([[12, 13, 14, 15]])]