In [5]:
import numpy as np

In [11]:
# Basic array creations
arr = np.array([1, 2, 3, 4])

In [12]:
arr

array([1, 2, 3, 4])

In [13]:
a = [1, 2, 3, 4.4, 5, 6]
a

[1, 2, 3, 4.4, 5, 6]

In [15]:
np.array(a)

array([1. , 2. , 3. , 4.4, 5. , 6. ])

In [16]:
l = [[1, 2, 3], [4, 5, 6], [7, 8, 9]]
l

[[1, 2, 3], [4, 5, 6], [7, 8, 9]]

In [17]:
np.array(l)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [18]:
# ARRAY GENERATION FUNCTIONS

In [19]:
arr = np.arange(1, 11, 2)

In [20]:
arr

array([1, 3, 5, 7, 9])

In [27]:
zero = np.zeros(6)

In [28]:
zero

array([0., 0., 0., 0., 0., 0.])

In [29]:
zero_s = np.zeros((4, 8))

In [30]:
zero_s

array([[0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0.]])

In [31]:
one_s = np.ones(6)

In [32]:
one_s

array([1., 1., 1., 1., 1., 1.])

In [33]:
ones_s = np.ones((6, 6))

In [34]:
ones_s

array([[1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.]])

In [39]:
spaces = np.linspace(0, 1, 100) # Spaces between 0 to 1

In [40]:
spaces

array([0.        , 0.01010101, 0.02020202, 0.03030303, 0.04040404,
       0.05050505, 0.06060606, 0.07070707, 0.08080808, 0.09090909,
       0.1010101 , 0.11111111, 0.12121212, 0.13131313, 0.14141414,
       0.15151515, 0.16161616, 0.17171717, 0.18181818, 0.19191919,
       0.2020202 , 0.21212121, 0.22222222, 0.23232323, 0.24242424,
       0.25252525, 0.26262626, 0.27272727, 0.28282828, 0.29292929,
       0.3030303 , 0.31313131, 0.32323232, 0.33333333, 0.34343434,
       0.35353535, 0.36363636, 0.37373737, 0.38383838, 0.39393939,
       0.4040404 , 0.41414141, 0.42424242, 0.43434343, 0.44444444,
       0.45454545, 0.46464646, 0.47474747, 0.48484848, 0.49494949,
       0.50505051, 0.51515152, 0.52525253, 0.53535354, 0.54545455,
       0.55555556, 0.56565657, 0.57575758, 0.58585859, 0.5959596 ,
       0.60606061, 0.61616162, 0.62626263, 0.63636364, 0.64646465,
       0.65656566, 0.66666667, 0.67676768, 0.68686869, 0.6969697 ,
       0.70707071, 0.71717172, 0.72727273, 0.73737374, 0.74747

In [41]:
# RANDOM GENERATION FUNCTIONS

In [42]:
np.random.rand(10)

array([0.45315166, 0.11669385, 0.67751625, 0.19704182, 0.40136782,
       0.3515868 , 0.07881135, 0.78948752, 0.47888028, 0.84636491])

In [43]:
np.random.randn(10)

array([ 0.62570834, -0.90927371,  0.63084661,  0.26941767, -0.59341509,
        0.56841424, -0.28350322,  1.06698211,  0.75378361,  0.72957958])

In [44]:
np.random.randint(10, 20, 10)

array([18, 12, 18, 18, 13, 15, 17, 12, 14, 13], dtype=int32)

In [45]:
# ARRAY ATTRIBUTES

In [46]:
arr = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])

In [47]:
arr

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [48]:
arr.shape

(3, 3)

In [49]:
arr.size

9

In [50]:
arr.dtype

dtype('int64')

In [51]:
# ARRAY METHOD

In [52]:
arr

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [53]:
arr.min()

np.int64(1)

In [54]:
arr.max()

np.int64(9)

In [55]:
arr.sum()

np.int64(45)

In [56]:
np.sum(arr, axis = 1)

array([ 6, 15, 24])

In [58]:
arr.mean()

np.float64(5.0)

In [59]:
arr.std()

np.float64(2.581988897471611)

In [61]:
arr.argmax()

np.int64(8)

In [62]:
arr.argmin()

np.int64(0)

In [63]:
# RESHAPING AND RESIZING

In [64]:
arr = np.arange(1, 31)

In [65]:
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30])

In [66]:
arr = arr.reshape(6, 5)

In [67]:
arr

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25],
       [26, 27, 28, 29, 30]])